const mongoose = require("mongoose");
const DigitalSchema = new mongoose.Schema({
  ArchitectDrawing: Boolean,
  DateOfConditionSurvey: String,
  LiquidatedDamage: String,
  Milestone: String,
  PPSService: String,
  Specification: String,
  advancePayment: String,
  bothPayment: Boolean,
  client: [{ address: String, individual: String, institute: String }],
  contractor: [
    {
      address: String,
      companyNo: String,
      individual: String,
      institute: String,
    },
  ],
  clientName: String,
  companyName: String,
  conpanyName: String,
  contractDate: String,
  contratorName: String,
  dateForCompletion: String,
  defectsLiabilityPeriod: String,
  digitalService: String,
  eachMilestone: String,
  isBothAgree: Boolean,
  isMilestone: Boolean,
  isProtection: Boolean,
  isRetention: Boolean,
  measurements: String,
  partyContact: Boolean,
  procurement: [String],
  requiredToAccess: Boolean,
  retention: String,
  scopeOfWork: String,
  siteAccess: String,
  siteRestrictions: String,
  todayDate: String,
  workCommencementDate: String,
  workingHours: String,
  surveyPhoto: [{ img: String, path: String }],
  clientSignature: [{ img: String, path: String }],
  contractorSigniture: [{ img: String, path: String }],
});

const DigitalContractModel = mongoose.model("digitalContract", DigitalSchema);

module.exports = DigitalContractModel;
